name: RFT Java CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Compile with Maven
        run: mvn -f NeptunApi/pom.xml compile
      - name: Test with Maven
        run: mvn test -B -f NeptunApi/pom.xml
        env:
          MAVEN_OPTS: -Dmaven.jacoco.version=0.8.7
        uses: bahmutov/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          maven-version: '3.8.4'
      - name: Coverage with JaCoCo
        if: always()
        run: mvn jacoco:report -f NeptunApi/pom.xml
      - name: Publish coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: neptun-coverage
          path: NeptunApi/target/site/jacoco
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save